#!/bin/sh

set -e

while ! nc -z postgres 5432; do
  sleep 0.1
done

echo "Database is up - executing command"

composer install
php artisan optimize
php artisan horizon:install
php artisan horizon:publish

exec "$@"
